/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadWindowsRouteImport } from './routes/download.windows'
import { Route as DownloadLinuxRouteImport } from './routes/download.linux'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadWindowsRoute = DownloadWindowsRouteImport.update({
  id: '/download/windows',
  path: '/download/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadLinuxRoute = DownloadLinuxRouteImport.update({
  id: '/download/linux',
  path: '/download/linux',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download/linux': typeof DownloadLinuxRoute
  '/download/windows': typeof DownloadWindowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/download/linux' | '/download/windows'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/download/linux' | '/download/windows'
  id: '__root__' | '/' | '/download/linux' | '/download/windows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadLinuxRoute: typeof DownloadLinuxRoute
  DownloadWindowsRoute: typeof DownloadWindowsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/windows': {
      id: '/download/windows'
      path: '/download/windows'
      fullPath: '/download/windows'
      preLoaderRoute: typeof DownloadWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/linux': {
      id: '/download/linux'
      path: '/download/linux'
      fullPath: '/download/linux'
      preLoaderRoute: typeof DownloadLinuxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadLinuxRoute: DownloadLinuxRoute,
  DownloadWindowsRoute: DownloadWindowsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
